# Generated by Django 4.1.7 on 2023-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('emaid', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('balance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsersDetails',
            fields=[
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('emaid', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('hint', models.CharField(max_length=255)),
            ],
        ),
    ]
