# Generated by Django 4.1.7 on 2023-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_savingaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='transaction',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
