# Generated by Django 4.1.7 on 2023-05-20 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_savingaccount_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='accountnumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
